import prettier from 'eslint-config-prettier'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { includeIgnoreFile } from '@eslint/compat'
import js from '@eslint/js'
import svelte from 'eslint-plugin-svelte'
import { defineConfig } from 'eslint/config'
import globals from 'globals'
import ts from 'typescript-eslint'

const gitignorePath = fileURLToPath(new URL('./.gitignore', import.meta.url))

// Domain isolation (docs/engineering/domain-module.md): a domain never imports another domain's code. Domains talk
// through facts, primitives, signals, intents and typed entity links; what two of them share lives in the shell or
// in the substrate. One block per domain id, for its folder in each app and in @eden/shared.
const domainIds = Object.keys(
	JSON.parse(readFileSync(new URL('./packages/ui-kit/src/lib/tokens/icon-list.json', import.meta.url), 'utf8')).domains
)
const isolation = domainIds.map((id) => {
	const others = domainIds.filter((other) => other !== id).join('|')
	// Sky's model, providers and store are in @eden/shared/weather
	const shared = id === 'weather' ? `domains/(?:${others})` : `(?:domains/(?:${others})|weather)`
	return {
		files: [`apps/*/src/lib/domains/${id}/**/*.{ts,svelte}`, `packages/shared/src/domains/${id}/**/*.ts`],
		rules: {
			'no-restricted-imports': [
				'error',
				{
					patterns: [
						{
							regex: `^(?:\\.\\./)+(?:${others})(?:/|$)|^\\$lib/domains/(?:${others})(?:/|$)|^@eden/shared/${shared}(?:/|$)`,
							message: `A domain never imports another domain ("${id}" is one): use a fact, a primitive, a signal, an intent or a typed link, or move what is shared to the shell.`,
						},
					],
				},
			],
		},
	}
})

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	{
		ignores: [
			'**/.svelte-kit',
			'**/dist',
			'**/storybook-static',
			'**/node_modules',
			'eden-design-system',
			// agent worktrees and local tooling state
			'.claude/**',
			// the Rust crate and the generated mobile projects; app build output; the static download page
			'src-tauri/**',
			'apps/*/build',
			'web/**',
			// generated by the token and icon builders
			'packages/ui-kit/src/lib/tokens/tokens.ts',
			'packages/ui-kit/src/lib/icons/icons.ts',
			'packages/ui-kit/src/lib/styles/prepaint.js',
			// generated by the registry builder
			'packages/shared/src/registry/generated.ts',
		],
	},
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	prettier,
	...svelte.configs.prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node },
		},
		rules: {
			// typescript-eslint recommends against no-undef on TypeScript projects
			'no-undef': 'off',
			'no-unused-vars': 'off',
			'@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
		},
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
			},
		},
	},
	{
		// The kit's own rules: see docs/engineering/ui-kit.md.
		files: ['packages/ui-kit/src/lib/**/*.{ts,svelte}'],
		rules: {
			// a SvelteKit rule; the kit is a library and may not import $app/paths
			'svelte/no-navigation-without-resolve': 'off',
			'svelte/no-at-html-tags': 'error',
			'svelte/require-each-key': 'error',
			'no-restricted-syntax': [
				'error',
				{
					selector: "CallExpression[callee.object.name='Math'][callee.property.name='random']",
					message: 'Ids come from $props.id(); the kit has no other need for randomness.',
				},
			],
			'no-restricted-imports': [
				'error',
				{
					paths: [{ name: 'svelte/store', message: 'No stores in the kit: use $state classes or context.' }],
					patterns: [{ group: ['$app/*'], message: 'The kit must not depend on SvelteKit runtime modules.' }],
				},
			],
		},
	},
	{
		// Components never listen on window or document directly; the attachments in src/lib/internal do.
		files: ['packages/ui-kit/src/lib/components/**/*.svelte', 'packages/ui-kit/src/lib/toast/**/*.svelte'],
		rules: {
			'no-restricted-syntax': [
				'error',
				{
					selector: "CallExpression[callee.object.name='Math'][callee.property.name='random']",
					message: 'Ids come from $props.id(); the kit has no other need for randomness.',
				},
				{
					selector:
						'CallExpression[callee.object.name=/^(window|document)$/][callee.property.name=/^(add|remove)EventListener$/]',
					message: 'Use an attachment from src/lib/internal instead of listening on window or document.',
				},
			],
		},
	},
	...isolation
)
