// icon-list.json + lucide-static → src/lib/icons/icons.ts: each glyph's nodes on Lucide's 24px grid and its drawn
// bounding box, which Icon.svelte uses to normalise every icon to one visual box. `--check` fails on drift.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { svgPathBbox } from 'svg-path-bbox'

const require = createRequire(import.meta.url)
const pkg = join(dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')
const list = JSON.parse(readFileSync(join(pkg, 'src/lib/tokens/icon-list.json'), 'utf8'))
const nodes = require('lucide-static/icon-nodes.json')

const fail = (msg) => {
	console.error(`build-icons: ${msg}`)
	process.exit(1)
}
const num = (v) => parseFloat(v)
const points = (s) =>
	String(s)
		.trim()
		.split(/[\s,]+/)
		.map(num)

/** [minX, minY, maxX, maxY] of one node */
function bbox([tag, a]) {
	switch (tag) {
		case 'path':
			return svgPathBbox(a.d)
		case 'circle':
			return [num(a.cx) - num(a.r), num(a.cy) - num(a.r), num(a.cx) + num(a.r), num(a.cy) + num(a.r)]
		case 'ellipse':
			return [num(a.cx) - num(a.rx), num(a.cy) - num(a.ry), num(a.cx) + num(a.rx), num(a.cy) + num(a.ry)]
		case 'rect':
			return [num(a.x), num(a.y), num(a.x) + num(a.width), num(a.y) + num(a.height)]
		case 'line':
			return [
				Math.min(num(a.x1), num(a.x2)),
				Math.min(num(a.y1), num(a.y2)),
				Math.max(num(a.x1), num(a.x2)),
				Math.max(num(a.y1), num(a.y2)),
			]
		case 'polyline':
		case 'polygon': {
			const p = points(a.points)
			const xs = p.filter((_, i) => i % 2 === 0)
			const ys = p.filter((_, i) => i % 2 === 1)
			return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)]
		}
		default:
			fail(`unsupported SVG element <${tag}>`)
	}
}
const round = (n) => Math.round(n * 100) / 100

const names = [...new Set(list.icons)]
if (names.length !== list.icons.length) fail('icon-list.json lists an icon twice')
for (const map of [list.domains, list.shell])
	for (const [id, icon] of Object.entries(map))
		if (!names.includes(icon)) fail(`"${id}" points at "${icon}", which is not in the icon list`)

const entries = names.map((name) => {
	const n = nodes[name]
	if (!n) {
		const near = Object.keys(nodes)
			.filter((k) => k.includes(name.split('-')[0]) || name.includes(k.split('-')[0]))
			.slice(0, 6)
		fail(
			`"${name}" is not a Lucide icon in lucide-static ${require('lucide-static/package.json').version}${near.length ? ` (near: ${near.join(', ')})` : ''}`
		)
	}
	const boxes = n.map(bbox)
	const x0 = Math.min(...boxes.map((b) => b[0]))
	const y0 = Math.min(...boxes.map((b) => b[1]))
	const x1 = Math.max(...boxes.map((b) => b[2]))
	const y1 = Math.max(...boxes.map((b) => b[3]))
	const attrs = (a) => Object.fromEntries(Object.entries(a).map(([k, v]) => [k, String(v)]))
	return { name, n: n.map(([tag, a]) => [tag, attrs(a)]), x: [round(x0), round(y0), round(x1 - x0), round(y1 - y0)] }
})

const body = entries
	.map((e) => `\t'${e.name}': {\n\t\tn: ${JSON.stringify(e.n)},\n\t\tx: [${e.x.join(', ')}],\n\t},`)
	.join('\n')
const content = `// GENERATED by scripts/build-icons.mjs from src/lib/tokens/icon-list.json and lucide-static (ISC). Do not edit; run \`yarn icons\`.
// Each icon: \`n\` the SVG nodes on Lucide's 24px grid, \`x\` the drawn bounding box [x, y, w, h] that Icon.svelte normalises.

export type IconNode = readonly [tag: string, attrs: Readonly<Record<string, string>>]
export interface IconDef {
	readonly n: readonly IconNode[]
	readonly x: readonly [x: number, y: number, w: number, h: number]
}

export const ICONS = {
${body}
} as const satisfies Record<string, IconDef>

export type IconName = keyof typeof ICONS
export const iconNames = Object.keys(ICONS) as IconName[]
`
const out = join(pkg, 'src/lib/icons/icons.ts')
if (check) {
	if (!existsSync(out) || readFileSync(out, 'utf8') !== content) {
		console.error('build-icons --check: src/lib/icons/icons.ts is out of date')
		process.exit(1)
	}
	console.log(`build-icons --check: ${entries.length} icons up to date.`)
} else {
	writeFileSync(out, content)
	console.log(`wrote ${relative(process.cwd(), out)}: ${entries.length} icons`)
}
