// GENERATED by scripts/build-tokens.mjs. The pre-paint script: run it as a blocking <script> in <head>, before the stylesheets
// are applied, so the first frame already carries the owner's theme, accent, brand level and font. It reads the eden:* keys the
// settings store writes and never sets data-face (a gallery-only dial). "system" resolves here; the app re-resolves on change.
;(function () {
	try {
		var root = document.documentElement
		var store = window.localStorage
		var theme = store.getItem('eden:theme') || 'system'
		if (theme !== 'light' && theme !== 'dark')
			theme = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
		root.setAttribute('data-theme', theme)
		var accent = store.getItem('eden:accent')
		if (accent && ["moss","fern","sage","clay","marigold","lavender","plum","sky","slate","rose"].indexOf(accent) !== -1) root.setAttribute('data-accent', accent)
		var brand = store.getItem('eden:brand')
		if (brand && ["plain","tended","lush"].indexOf(brand) !== -1) root.setAttribute('data-brand', brand)
		var font = store.getItem('eden:font')
		if (font) root.setAttribute('data-font', font)
		if (store.getItem('eden:density') === 'compact') root.setAttribute('data-density', 'compact')
	} catch (e) {
		/* no storage, no attributes: the stylesheet defaults are light, moss, lush */
	}
})()
