// Staged here until the Android project exists: `src-tauri/gen/android` is generated by `tauri android init`, and this
// file is copied into it (docs/engineering/data-layer.md, "The Android checklist"). The `package` line and
// `DB_KEY_CLASS` in `src/db/key_provider.rs` both follow the Android namespace.
package com.palekodama.eden

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.io.IOException
import java.security.KeyStore
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The database key, held by the Android Keystore.
 *
 * Called from Rust over JNI (`src/db/key_provider.rs`). The Keystore never gives up raw key material, so the key is
 * wrapped: an AES-256-GCM key that cannot leave the Keystore encrypts a random 64-character hex passphrase, and the
 * wrapped form is kept in app-private SharedPreferences. It survives an update of the app and dies with an
 * uninstall, as the iOS Keychain item does.
 *
 * If a wrapped blob exists and cannot be decrypted, this THROWS. A fresh key would not match the database the first
 * one encrypted. Rust turns the exception into a key storage error.
 */
object EdenDbKey {
    private const val KEYSTORE_ALIAS = "eden_sqlcipher_wrap_v1"
    private const val PREFS_FILE = "eden_db_key"
    private const val PREFS_KEY_WRAPPED = "wrapped_key_v1"
    private const val GCM_TAG_BITS = 128
    private const val KEY_HEX_CHARS = 64

    @JvmStatic
    @Synchronized
    fun getOrCreateKey(context: Context): String {
        val prefs = context.applicationContext.getSharedPreferences(PREFS_FILE, Context.MODE_PRIVATE)

        val wrapped = prefs.getString(PREFS_KEY_WRAPPED, null)
        if (wrapped != null) {
            return unwrap(wrapped)
        }

        // First launch. commit(), not apply(): a crash right after must not lose the only copy of the key for a
        // database that is about to be created.
        val hexKey = generateHexKey()
        val blob = wrap(hexKey)
        if (!prefs.edit().putString(PREFS_KEY_WRAPPED, blob).commit()) {
            throw IOException("failed to persist the wrapped database key")
        }
        return hexKey
    }

    /** 32 random bytes as 64 lowercase hex characters, the format of the desktop and iOS keys. */
    private fun generateHexKey(): String {
        val bytes = ByteArray(KEY_HEX_CHARS / 2)
        SecureRandom().nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }

    /** Encrypts the passphrase with the Keystore key; returns `Base64(iv):Base64(ciphertext)`. */
    private fun wrap(hexKey: String): String {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateWrappingKey())
        val ciphertext = cipher.doFinal(hexKey.toByteArray(Charsets.UTF_8))
        val iv = Base64.encodeToString(cipher.iv, Base64.NO_WRAP)
        val ct = Base64.encodeToString(ciphertext, Base64.NO_WRAP)
        return "$iv:$ct"
    }

    /** Decrypts a wrapped blob. Throws on any corruption or Keystore failure; never generates a new key. */
    private fun unwrap(blob: String): String {
        val parts = blob.split(':')
        require(parts.size == 2) { "malformed wrapped key blob" }
        val iv = Base64.decode(parts[0], Base64.NO_WRAP)
        val ct = Base64.decode(parts[1], Base64.NO_WRAP)

        val keystore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        val key = keystore.getKey(KEYSTORE_ALIAS, null) as? SecretKey
            ?: throw IllegalStateException("the wrapped key blob exists but its Keystore alias is missing")

        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        return String(cipher.doFinal(ct), Charsets.UTF_8)
    }

    /**
     * Loads or creates the wrapping key. It carries no user-authentication constraint: the database must open after
     * the first unlock without a prompt, as on iOS.
     */
    private fun getOrCreateWrappingKey(): SecretKey {
        val keystore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (keystore.getKey(KEYSTORE_ALIAS, null) as? SecretKey)?.let { return it }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        generator.init(
            KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }
}
