// Staged here until the Android project exists: `src-tauri/gen/android` is generated by `tauri android init`, and this
// file is copied into it beside `EdenDbKey.kt` (docs/engineering/data-layer.md, "The Android checklist"). The
// `package` line and `SECRETS_CLASS` in `src/db/secret_store.rs` both follow the Android namespace.
package com.palekodama.eden

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.io.IOException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The owner's secrets (the Gardener's provider key), held by the Android Keystore.
 *
 * Called from Rust over JNI (`src/db/secret_store.rs`). The Keystore never gives up raw key material, so each
 * secret is wrapped: an AES-256-GCM key that cannot leave the Keystore encrypts the value, and the wrapped form is
 * kept under the secret's name in app-private SharedPreferences. It survives an update of the app and dies with an
 * uninstall, as the iOS Keychain item does.
 *
 * If a wrapped blob exists and cannot be decrypted, `get` THROWS rather than answering null: a secret that is there
 * and cannot be read is an error, never silently gone. Rust turns the exception into a key storage error.
 */
object EdenSecrets {
    private const val KEYSTORE_ALIAS = "eden_secrets"
    private const val PREFS_FILE = "eden_secrets"
    private const val GCM_TAG_BITS = 128

    @JvmStatic
    @Synchronized
    fun get(context: Context, name: String): String? {
        val wrapped = prefs(context).getString(name, null) ?: return null
        return unwrap(wrapped)
    }

    @JvmStatic
    @Synchronized
    fun set(context: Context, name: String, value: String) {
        val blob = wrap(value)
        // commit(), not apply(): the caller is told the secret is kept only once it is.
        if (!prefs(context).edit().putString(name, blob).commit()) {
            throw IOException("failed to persist the secret $name")
        }
    }

    /** Removes the secret. Answers whether there was one. */
    @JvmStatic
    @Synchronized
    fun delete(context: Context, name: String): Boolean {
        val prefs = prefs(context)
        if (!prefs.contains(name)) {
            return false
        }
        if (!prefs.edit().remove(name).commit()) {
            throw IOException("failed to remove the secret $name")
        }
        return true
    }

    private fun prefs(context: Context) =
        context.applicationContext.getSharedPreferences(PREFS_FILE, Context.MODE_PRIVATE)

    /** Encrypts a value with the Keystore key; returns `Base64(iv):Base64(ciphertext)`. */
    private fun wrap(value: String): String {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateWrappingKey())
        val ciphertext = cipher.doFinal(value.toByteArray(Charsets.UTF_8))
        val iv = Base64.encodeToString(cipher.iv, Base64.NO_WRAP)
        val ct = Base64.encodeToString(ciphertext, Base64.NO_WRAP)
        return "$iv:$ct"
    }

    /** Decrypts a wrapped blob. Throws on any corruption or Keystore failure; never answers null for one. */
    private fun unwrap(blob: String): String {
        val parts = blob.split(':')
        require(parts.size == 2) { "malformed wrapped secret blob" }
        val iv = Base64.decode(parts[0], Base64.NO_WRAP)
        val ct = Base64.decode(parts[1], Base64.NO_WRAP)

        val keystore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        val key = keystore.getKey(KEYSTORE_ALIAS, null) as? SecretKey
            ?: throw IllegalStateException("a wrapped secret exists but its Keystore alias is missing")

        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, iv))
        return String(cipher.doFinal(ct), Charsets.UTF_8)
    }

    /**
     * Loads or creates the wrapping key. It carries no user-authentication constraint: the Gardener runs after the
     * first unlock without a prompt, as on iOS.
     */
    private fun getOrCreateWrappingKey(): SecretKey {
        val keystore = KeyStore.getInstance("AndroidKeyStore").apply { load(null) }
        (keystore.getKey(KEYSTORE_ALIAS, null) as? SecretKey)?.let { return it }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore")
        generator.init(
            KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return generator.generateKey()
    }
}
