// GENERATED by scripts/build-tokens.mjs from tokens.json. Do not edit; run `yarn tokens`.

export const themes = ["light", "dark"] as const
export type Theme = (typeof themes)[number]

export const accents = ["moss", "fern", "sage", "clay", "marigold", "lavender", "plum", "sky", "slate", "rose"] as const
export type Accent = (typeof accents)[number]

export const brandLevels = ["plain", "tended", "lush"] as const
export type BrandLevel = (typeof brandLevels)[number]

export const faces = ["newsreader", "fraunces", "instrument", "bricolage"] as const
export type Face = (typeof faces)[number]

export const platforms = ["desktop", "mobile"] as const
export type Platform = (typeof platforms)[number]

export const densities = ["comfortable", "compact"] as const
export type Density = (typeof densities)[number]

export const reliefs = ["raised", "flat"] as const
export type Relief = (typeof reliefs)[number]

export const typeStyleNames = ["display-xl", "display-lg", "display-md", "display-sm", "voice", "daily-line", "daily-line-lg", "body-lg", "body", "body-sm", "label", "title", "title-lg", "caption", "data-lg", "data", "data-sm", "code"] as const
export type TypeStyle = (typeof typeStyleNames)[number]

export const colorTokenNames = ["surface-0", "surface-1", "surface-2", "surface-3", "text-primary", "text-secondary", "text-tertiary", "stroke", "stroke-subtle", "stroke-hover", "brand-primary", "brand-hover", "brand-muted", "on-brand", "ai", "ai-muted", "honey", "honey-muted", "on-honey", "on-ai", "danger", "on-danger", "warning", "info", "success", "accent-moss", "accent-fern", "accent-sage", "accent-clay", "accent-marigold", "accent-lavender", "accent-plum", "accent-sky", "accent-slate", "accent-rose", "chart-primary", "chart-reference", "chart-series-2", "chart-series-3", "chart-series-4", "chart-axis", "chart-grid", "chart-label"] as const
export type ColorToken = (typeof colorTokenNames)[number]

export const defaults = {
	theme: "light",
	accent: "moss",
	brand: "lush",
	face: "newsreader",
	platform: "desktop",
	density: "comfortable",
	relief: "raised",
} as const

/** Resolved colour values per theme (aliases followed), for swatches and tests. The CSS is the runtime source. */
export const colors = {
	"light": {
		"surface-0": "#f6f4ec",
		"surface-1": "#efede3",
		"surface-2": "#e6e3d6",
		"surface-3": "#dcd8c8",
		"text-primary": "#1f2a22",
		"text-secondary": "#4c5a50",
		"text-tertiary": "#7c8a7f",
		"stroke": "#d9d6c8",
		"stroke-subtle": "#e8e5d9",
		"stroke-hover": "#c4c1b1",
		"brand-primary": "#4f7a5a",
		"brand-hover": "#43684d",
		"brand-muted": "#dce8dd",
		"on-brand": "#ffffff",
		"ai": "#1e6e5c",
		"ai-muted": "#d9efe6",
		"honey": "#8a6a1e",
		"honey-muted": "#f1e6c4",
		"on-honey": "#ffffff",
		"on-ai": "#ffffff",
		"danger": "#b0413e",
		"on-danger": "#ffffff",
		"warning": "#b8821f",
		"info": "#4a82a6",
		"success": "#4f7a5a",
		"accent-moss": "#4f7a5a",
		"accent-fern": "#3e8e5e",
		"accent-sage": "#6f8f7c",
		"accent-clay": "#b5644a",
		"accent-marigold": "#c98a2e",
		"accent-lavender": "#7b6fae",
		"accent-plum": "#7a4b72",
		"accent-sky": "#4a82a6",
		"accent-slate": "#5b6b78",
		"accent-rose": "#b3606f",
		"chart-primary": "#4f7a5a",
		"chart-reference": "#7c8a7f",
		"chart-series-2": "#b5644a",
		"chart-series-3": "#4a82a6",
		"chart-series-4": "#c98a2e",
		"chart-axis": "#d9d6c8",
		"chart-grid": "#e8e5d9",
		"chart-label": "#4c5a50"
	},
	"dark": {
		"surface-0": "#0f1512",
		"surface-1": "#16201b",
		"surface-2": "#1e2a24",
		"surface-3": "#26332c",
		"text-primary": "#e6ebe4",
		"text-secondary": "#a9b5ac",
		"text-tertiary": "#75837a",
		"stroke": "#2a3730",
		"stroke-subtle": "#1f2a24",
		"stroke-hover": "#364840",
		"brand-primary": "#7fb58a",
		"brand-hover": "#93c49d",
		"brand-muted": "#24382c",
		"on-brand": "#0f1512",
		"ai": "#86d6bf",
		"ai-muted": "#163329",
		"honey": "#f2d27a",
		"honey-muted": "#2e2a18",
		"on-honey": "#0f1512",
		"on-ai": "#0f1512",
		"danger": "#e0706c",
		"on-danger": "#0f1512",
		"warning": "#e3b24f",
		"info": "#7fb2d6",
		"success": "#7fb58a",
		"accent-moss": "#7fb58a",
		"accent-fern": "#8cd3a0",
		"accent-sage": "#a3c4b1",
		"accent-clay": "#d98b6e",
		"accent-marigold": "#e8b45a",
		"accent-lavender": "#a9a0d8",
		"accent-plum": "#b07aa6",
		"accent-sky": "#7fb2d6",
		"accent-slate": "#93a3b0",
		"accent-rose": "#d9899a",
		"chart-primary": "#7fb58a",
		"chart-reference": "#75837a",
		"chart-series-2": "#d98b6e",
		"chart-series-3": "#7fb2d6",
		"chart-series-4": "#e8b45a",
		"chart-axis": "#2a3730",
		"chart-grid": "#1f2a24",
		"chart-label": "#a9b5ac"
	}
} as const satisfies Record<Theme, Record<ColorToken, string>>

export const typeStyles = {
	"display-xl": {
		"family": "display",
		"size": 36,
		"lineHeight": 1.15,
		"weight": "display",
		"opsz": 36,
		"tracking": "-0.01em",
		"sample": "Garden",
		"usage": "The one title on a full-height screen: onboarding steps, the splash wordmark at 'eden'."
	},
	"display-lg": {
		"family": "display",
		"size": 28,
		"lineHeight": 1.15,
		"weight": "display",
		"opsz": 28,
		"tracking": "-0.01em",
		"sample": "Hearth",
		"usage": "Page header names on desktop; the Sanctuary line at full size."
	},
	"display-md": {
		"family": "display",
		"size": 22,
		"lineHeight": 1.15,
		"weight": "display",
		"opsz": 22,
		"sample": "Nothing in the fridge yet",
		"usage": "Empty-state titles, sheet titles, section headings inside a detail pane."
	},
	"display-sm": {
		"family": "display",
		"size": 18,
		"lineHeight": 1.15,
		"weight": "display",
		"opsz": 18,
		"sample": "This week",
		"usage": "Widget-sized headings on mobile and in L widgets."
	},
	"voice": {
		"family": "display",
		"size": 15,
		"lineHeight": 22,
		"weight": 400,
		"opsz": 15,
		"sample": "82.4 kg logged. Undo",
		"usage": "A sentence the app says, in the display face so it matches the buttons beside it: toast messages, notification lines, Gardener replies, empty-state and inline-error sentences, popover text. Never for the owner's data, lists, tables or anything typed."
	},
	"daily-line": {
		"family": "display",
		"size": 22,
		"lineHeight": 1.35,
		"weight": 400,
		"opsz": 22,
		"italic": true,
		"sample": "Tend what you can reach.",
		"usage": "The daily line on the splash, the Garden and Sanctuary, with its source beneath in caption. Italic is reserved for this style."
	},
	"daily-line-lg": {
		"family": "display",
		"size": 28,
		"lineHeight": 1.35,
		"weight": 400,
		"opsz": 28,
		"italic": true,
		"sample": "Tend what you can reach.",
		"usage": "The daily line on the splash and the Sanctuary page: the same italic voice at the display-lg size, still weight 400 and the looser leading."
	},
	"body-lg": {
		"family": "sans",
		"size": 16,
		"lineHeight": 24,
		"weight": 400,
		"sample": "From your stock and three recipes, here are two you can cook tonight.",
		"usage": "Body on mobile, onboarding copy, Gardener replies on mobile."
	},
	"body": {
		"family": "sans",
		"size": 14,
		"lineHeight": 21,
		"weight": 400,
		"sample": "Spinach and avocados expire tomorrow.",
		"usage": "Body on desktop: list primary text, messages, form values, notification lines."
	},
	"body-sm": {
		"family": "sans",
		"size": 13,
		"lineHeight": 20,
		"weight": 400,
		"sample": "Fridge · expires Thu",
		"usage": "The secondary line of a row, chip labels, helper text, the audit log."
	},
	"label": {
		"family": "sans",
		"size": 13,
		"lineHeight": 20,
		"weight": 500,
		"sample": "Capture a haul",
		"usage": "Buttons, segmented-control tabs, field labels, badge text, sidebar items."
	},
	"title": {
		"family": "sans",
		"size": 14,
		"lineHeight": 20,
		"weight": 600,
		"sample": "Expiring soon",
		"usage": "Widget title rows, inbox card titles, table headers, detail-pane section titles."
	},
	"title-lg": {
		"family": "sans",
		"size": 18,
		"lineHeight": 26,
		"weight": 600,
		"sample": "Miso-glazed salmon with spinach",
		"usage": "The title of a detail pane or pushed view."
	},
	"caption": {
		"family": "sans",
		"size": 12,
		"lineHeight": 18,
		"weight": 400,
		"tracking": "0.01em",
		"sample": "Food, recipes, pantry, groceries",
		"usage": "Domain subtitles, timestamps, the daily line's source, status-bar text. Usually in text-secondary or text-tertiary."
	},
	"data-lg": {
		"family": "mono",
		"size": 28,
		"lineHeight": 1.15,
		"weight": 500,
		"sample": "82.4",
		"usage": "The value in the Quick Log sheet, the headline metric in a widget, the budget meter's figure."
	},
	"data": {
		"family": "mono",
		"size": 14,
		"lineHeight": 21,
		"weight": 400,
		"sample": "900 g",
		"usage": "Numbers in tables, quantities in stock rows, costs and token counts."
	},
	"data-sm": {
		"family": "mono",
		"size": 13,
		"lineHeight": 20,
		"weight": 400,
		"sample": "07:40",
		"usage": "Trailing metadata in list rows, times, the unit chip, registry-id counts in the can-see chip."
	},
	"code": {
		"family": "mono",
		"size": 13,
		"lineHeight": 20,
		"weight": 400,
		"sample": "eden://recipe/01J9…",
		"usage": "Code, entity URIs, registry ids and device names in Toolbench and Settings."
	}
} as const

export const spacing = {
	"space-1": "4px",
	"space-2": "8px",
	"space-3": "12px",
	"space-4": "16px",
	"space-6": "24px",
	"space-8": "32px"
} as const
export const radius = {
	"radius-control": "6px",
	"radius-card": "10px",
	"radius-sheet": "16px",
	"radius-full": "9999px"
} as const
export const sizes = {
	"row-comfortable": "40px",
	"row-compact": "32px",
	"control-height": "32px",
	"touch-target": "44px",
	"icon-sm": "16px",
	"icon-md": "20px",
	"icon-lg": "24px",
	"icon-stroke-dense": "1.75px",
	"icon-stroke": "2px",
	"focus-ring-width": "2px",
	"focus-ring-offset": "2px",
	"widget-columns": "4",
	"field-lg": "56px",
	"tab-bar": "56px",
	"fab": "56px",
	"sidebar": "220px",
	"status-bar": "36px",
	"sheet-sm": "360px",
	"sheet-md": "440px",
	"sheet-max": "900px"
} as const
export const motion = {
	"duration-micro": "150ms",
	"duration-panel": "220ms",
	"duration-settle": "320ms",
	"duration-breeze": "700ms",
	"ease-out": "cubic-bezier(0.22, 1, 0.36, 1)"
} as const
export const zIndex = {
	"sticky": 10,
	"sidebar": 20,
	"status": 30,
	"popover": 1000,
	"sheet": 1100,
	"toast": 1200
} as const
export const breakpoints = {
	"phone": 480,
	"tablet": 768,
	"detail": 1100,
	"wide": 1440
} as const

/** localStorage keys the pre-paint script and the settings store share. */
export const storageKeys = {
	theme: 'eden:theme',
	accent: 'eden:accent',
	brand: 'eden:brand',
	font: 'eden:font',
	density: 'eden:density',
} as const
