// GENERATED by packages/shared/scripts/build-registry.mjs from the domains' manifest.json files,
// registry/substrate.json, registry/planned.json and manifest/shell.json. Do not edit; run `yarn registry`.

/** Every resource a grant, a declared read or an audit entry can name (D-35); `live` is what a write may create. */
export const RESOURCES = [
	{
		"id": "preferred-name",
		"category": "fact",
		"primitive": null,
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "home-area",
		"category": "fact",
		"primitive": null,
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "task",
		"category": "primitive",
		"primitive": null,
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "event",
		"category": "primitive",
		"primitive": null,
		"owner": "substrate",
		"tier": "by-kind",
		"phase": 1,
		"live": true
	},
	{
		"id": "place",
		"category": "primitive",
		"primitive": null,
		"owner": "substrate",
		"tier": "by-kind",
		"phase": 1,
		"live": true
	},
	{
		"id": "attachment",
		"category": "primitive",
		"primitive": null,
		"owner": "substrate",
		"tier": "by-kind",
		"phase": 1,
		"live": true
	},
	{
		"id": "calendar-source",
		"category": "entity",
		"primitive": null,
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "todo",
		"category": "kind",
		"primitive": "task",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "checklist",
		"category": "kind",
		"primitive": "task",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "routine",
		"category": "kind",
		"primitive": "task",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "habit",
		"category": "kind",
		"primitive": "task",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "reminder",
		"category": "kind",
		"primitive": "task",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "local-event",
		"category": "kind",
		"primitive": "event",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "home",
		"category": "kind",
		"primitive": "place",
		"owner": "substrate",
		"tier": "T2",
		"phase": 1,
		"live": true
	},
	{
		"id": "venue",
		"category": "kind",
		"primitive": "place",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "document",
		"category": "kind",
		"primitive": "attachment",
		"owner": "substrate",
		"tier": "T2",
		"phase": 1,
		"live": true
	},
	{
		"id": "photo",
		"category": "kind",
		"primitive": "attachment",
		"owner": "substrate",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "identity-document",
		"category": "kind",
		"primitive": "attachment",
		"owner": "substrate",
		"tier": "T3",
		"phase": 2,
		"live": false
	},
	{
		"id": "allergy",
		"category": "fact",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T2",
		"phase": 1,
		"live": true
	},
	{
		"id": "dietary-preference",
		"category": "fact",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "disliked-ingredient",
		"category": "fact",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "cuisine-preference",
		"category": "fact",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "household-size",
		"category": "fact",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "stock-item",
		"category": "entity",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "recipe",
		"category": "entity",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "grocery-list",
		"category": "entity",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "grocery-item",
		"category": "entity",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "storage-tip",
		"category": "entity",
		"primitive": null,
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "shop-day",
		"category": "kind",
		"primitive": "event",
		"owner": "kitchen",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "haul-photo",
		"category": "kind",
		"primitive": "attachment",
		"owner": "kitchen",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "skill",
		"category": "fact",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "owned-hardware",
		"category": "fact",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "preferred-tool",
		"category": "fact",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "idea",
		"category": "entity",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "project",
		"category": "entity",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "device",
		"category": "entity",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T2",
		"phase": 1,
		"live": true
	},
	{
		"id": "parts-list",
		"category": "entity",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "sketch",
		"category": "entity",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "note",
		"category": "entity",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "brainstorm-session",
		"category": "entity",
		"primitive": null,
		"owner": "toolbench",
		"tier": "T1",
		"phase": 1,
		"live": true
	},
	{
		"id": "render",
		"category": "kind",
		"primitive": "attachment",
		"owner": "toolbench",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "forecast",
		"category": "entity",
		"primitive": null,
		"owner": "weather",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "alert",
		"category": "entity",
		"primitive": null,
		"owner": "weather",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "ephemeris",
		"category": "entity",
		"primitive": null,
		"owner": "weather",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "air-quality",
		"category": "entity",
		"primitive": null,
		"owner": "weather",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "allergens",
		"category": "entity",
		"primitive": null,
		"owner": "weather",
		"tier": "T0",
		"phase": 1,
		"live": true
	},
	{
		"id": "layer",
		"category": "entity",
		"primitive": null,
		"owner": "calendar",
		"tier": "T0",
		"phase": 2,
		"live": false
	},
	{
		"id": "holiday-set",
		"category": "entity",
		"primitive": null,
		"owner": "calendar",
		"tier": "T0",
		"phase": 2,
		"live": false
	},
	{
		"id": "google-event",
		"category": "kind",
		"primitive": "event",
		"owner": "calendar",
		"tier": "by-source",
		"phase": 2,
		"live": false
	},
	{
		"id": "ics-event",
		"category": "kind",
		"primitive": "event",
		"owner": "calendar",
		"tier": "by-source",
		"phase": "later",
		"live": false
	},
	{
		"id": "gym-preference",
		"category": "fact",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "training-schedule",
		"category": "fact",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "equipment",
		"category": "fact",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "fitness-goal",
		"category": "fact",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "favorite-supplement",
		"category": "fact",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "training-limitation",
		"category": "fact",
		"primitive": null,
		"owner": "fitness",
		"tier": "T2",
		"phase": 2,
		"live": false
	},
	{
		"id": "current-weight",
		"category": "fact",
		"primitive": null,
		"owner": "fitness",
		"tier": "T2",
		"phase": 2,
		"live": false
	},
	{
		"id": "exercise",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T0",
		"phase": 2,
		"live": false
	},
	{
		"id": "workout-template",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "workout-log",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "gym",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "training-goal",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "body-metric",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T2",
		"phase": 2,
		"live": false
	},
	{
		"id": "supplement",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "intake-log",
		"category": "entity",
		"primitive": null,
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "workout-session",
		"category": "kind",
		"primitive": "event",
		"owner": "fitness",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "followed-tradition",
		"category": "fact",
		"primitive": null,
		"owner": "spirit",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "value",
		"category": "fact",
		"primitive": null,
		"owner": "spirit",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "favorite-author",
		"category": "fact",
		"primitive": null,
		"owner": "spirit",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "birth-data",
		"category": "fact",
		"primitive": null,
		"owner": "spirit",
		"tier": "T2",
		"phase": 2,
		"live": false
	},
	{
		"id": "tradition",
		"category": "entity",
		"primitive": null,
		"owner": "spirit",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "reading-source",
		"category": "entity",
		"primitive": null,
		"owner": "spirit",
		"tier": "T0",
		"phase": 2,
		"live": false
	},
	{
		"id": "excerpt",
		"category": "entity",
		"primitive": null,
		"owner": "spirit",
		"tier": "T0",
		"phase": 2,
		"live": false
	},
	{
		"id": "author",
		"category": "entity",
		"primitive": null,
		"owner": "spirit",
		"tier": "T0",
		"phase": 2,
		"live": false
	},
	{
		"id": "reading-log",
		"category": "entity",
		"primitive": null,
		"owner": "spirit",
		"tier": "T1",
		"phase": 2,
		"live": false
	},
	{
		"id": "astrology-profile",
		"category": "entity",
		"primitive": null,
		"owner": "spirit",
		"tier": "T2",
		"phase": 2,
		"live": false
	},
	{
		"id": "favorite-vibe",
		"category": "fact",
		"primitive": null,
		"owner": "places",
		"tier": "T0",
		"phase": 3,
		"live": false
	},
	{
		"id": "place-profile",
		"category": "entity",
		"primitive": null,
		"owner": "places",
		"tier": "T1",
		"phase": 3,
		"live": false
	},
	{
		"id": "vibe",
		"category": "entity",
		"primitive": null,
		"owner": "places",
		"tier": "T0",
		"phase": 3,
		"live": false
	},
	{
		"id": "collection",
		"category": "entity",
		"primitive": null,
		"owner": "places",
		"tier": "T1",
		"phase": 3,
		"live": false
	},
	{
		"id": "listing",
		"category": "entity",
		"primitive": null,
		"owner": "places",
		"tier": "T0",
		"phase": 3,
		"live": false
	},
	{
		"id": "visit",
		"category": "entity",
		"primitive": null,
		"owner": "places",
		"tier": "T1",
		"phase": 3,
		"live": false
	},
	{
		"id": "outing",
		"category": "kind",
		"primitive": "event",
		"owner": "places",
		"tier": "T1",
		"phase": 3,
		"live": false
	},
	{
		"id": "medical-dietary-restriction",
		"category": "fact",
		"primitive": null,
		"owner": "health",
		"tier": "T2",
		"phase": 1,
		"live": true
	},
	{
		"id": "blood-type",
		"category": "fact",
		"primitive": null,
		"owner": "health",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "condition",
		"category": "entity",
		"primitive": null,
		"owner": "health",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "medication",
		"category": "entity",
		"primitive": null,
		"owner": "health",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "appointment-note",
		"category": "entity",
		"primitive": null,
		"owner": "health",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "provider",
		"category": "entity",
		"primitive": null,
		"owner": "health",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "insurance-plan",
		"category": "entity",
		"primitive": null,
		"owner": "health",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "medical-appointment",
		"category": "kind",
		"primitive": "event",
		"owner": "health",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "insurance-card",
		"category": "kind",
		"primitive": "attachment",
		"owner": "health",
		"tier": "T3",
		"phase": "later",
		"live": false
	},
	{
		"id": "monthly-income-band",
		"category": "fact",
		"primitive": null,
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "savings-goal",
		"category": "fact",
		"primitive": null,
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "account",
		"category": "entity",
		"primitive": null,
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "transaction",
		"category": "entity",
		"primitive": null,
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "budget",
		"category": "entity",
		"primitive": null,
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "budget-category",
		"category": "entity",
		"primitive": null,
		"owner": "finance",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "recurring-charge",
		"category": "entity",
		"primitive": null,
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "holding",
		"category": "entity",
		"primitive": null,
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "receipt",
		"category": "kind",
		"primitive": "attachment",
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "bill-due",
		"category": "kind",
		"primitive": "event",
		"owner": "finance",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "person",
		"category": "entity",
		"primitive": null,
		"owner": "people",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "interaction",
		"category": "entity",
		"primitive": null,
		"owner": "people",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "birthday",
		"category": "kind",
		"primitive": "event",
		"owner": "people",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "entry",
		"category": "entity",
		"primitive": null,
		"owner": "journal",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "prompt",
		"category": "entity",
		"primitive": null,
		"owner": "journal",
		"tier": "T0",
		"phase": "later",
		"live": false
	},
	{
		"id": "home-airport",
		"category": "fact",
		"primitive": null,
		"owner": "travel",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "seat-preference",
		"category": "fact",
		"primitive": null,
		"owner": "travel",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "passport-expiry",
		"category": "fact",
		"primitive": null,
		"owner": "travel",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "trip",
		"category": "entity",
		"primitive": null,
		"owner": "travel",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "itinerary-item",
		"category": "entity",
		"primitive": null,
		"owner": "travel",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "trip-document",
		"category": "entity",
		"primitive": null,
		"owner": "travel",
		"tier": "T2",
		"phase": "later",
		"live": false
	},
	{
		"id": "trip-destination",
		"category": "kind",
		"primitive": "place",
		"owner": "travel",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "trip-item",
		"category": "kind",
		"primitive": "event",
		"owner": "travel",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "reading-interest",
		"category": "fact",
		"primitive": null,
		"owner": "library",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "reading-item",
		"category": "entity",
		"primitive": null,
		"owner": "library",
		"tier": "T1",
		"phase": "later",
		"live": false
	},
	{
		"id": "highlight",
		"category": "entity",
		"primitive": null,
		"owner": "library",
		"tier": "T1",
		"phase": "later",
		"live": false
	}
] as const

/** The built domains' declarations, by id, in the shell's order. */
export const DECLARATIONS = {
	"kitchen": {
		"id": "kitchen",
		"phase": 1,
		"name": "domains.kitchen.name",
		"subtitle": "domains.kitchen.subtitle",
		"sidebar": {
			"group": "domains",
			"order": 10,
			"visible": true
		},
		"tabs": [
			{
				"id": "stock",
				"label": "domains.kitchen.tabs.stock"
			},
			{
				"id": "recipes",
				"label": "domains.kitchen.tabs.recipes"
			},
			{
				"id": "grocery",
				"label": "domains.kitchen.tabs.grocery"
			},
			{
				"id": "tips",
				"label": "domains.kitchen.tabs.tips"
			}
		],
		"resources": [
			"allergy",
			"dietary-preference",
			"disliked-ingredient",
			"cuisine-preference",
			"household-size",
			"stock-item",
			"recipe",
			"grocery-list",
			"grocery-item",
			"storage-tip",
			"shop-day",
			"haul-photo"
		],
		"reads": [
			"medical-dietary-restriction",
			"favorite-supplement",
			"home-area"
		],
		"widgets": [
			{
				"id": "expiring-soon",
				"sizes": [
					"s",
					"m"
				],
				"default": true,
				"planned": false,
				"reads": [
					"stock-item"
				],
				"title": "garden.widgets.expiringSoon",
				"empty": "garden.empty.expiringSoon"
			},
			{
				"id": "cook-tonight",
				"sizes": [
					"m"
				],
				"default": true,
				"planned": false,
				"reads": [
					"stock-item",
					"recipe",
					"dietary-preference",
					"allergy",
					"medical-dietary-restriction"
				],
				"title": "garden.widgets.cookTonight",
				"empty": "garden.empty.cookTonight"
			},
			{
				"id": "grocery-quick-add",
				"sizes": [
					"s"
				],
				"default": false,
				"planned": true,
				"reads": [
					"grocery-list",
					"grocery-item"
				],
				"title": "garden.widgets.groceryQuickAdd",
				"empty": "garden.empty.groceryQuickAdd"
			}
		],
		"quickActions": [
			{
				"id": "capture-haul",
				"label": "domains.kitchen.capture.action",
				"icon": "camera"
			},
			{
				"id": "add-to-grocery",
				"label": "domains.kitchen.grocery.add",
				"icon": "plus"
			}
		],
		"captureSources": [
			"photo",
			"receipt"
		],
		"tools": [
			{
				"id": "suggest-recipes",
				"access": "read",
				"confirm": false,
				"reads": [
					"stock-item",
					"recipe",
					"dietary-preference",
					"disliked-ingredient",
					"cuisine-preference",
					"allergy",
					"medical-dietary-restriction"
				]
			},
			{
				"id": "storage-tip",
				"access": "read",
				"confirm": false,
				"reads": [
					"stock-item",
					"storage-tip"
				]
			},
			{
				"id": "capture-haul",
				"access": "write-draft",
				"confirm": false,
				"reads": []
			},
			{
				"id": "draft-grocery-list",
				"access": "write-draft",
				"confirm": false,
				"reads": [
					"stock-item",
					"recipe",
					"grocery-list",
					"grocery-item"
				]
			},
			{
				"id": "add-stock",
				"access": "write",
				"confirm": true,
				"reads": [
					"stock-item"
				]
			},
			{
				"id": "plan-week",
				"access": "write-draft",
				"confirm": false,
				"reads": [
					"stock-item",
					"recipe",
					"local-event",
					"task"
				]
			}
		],
		"signals": [
			"stock.expiring",
			"stock.low",
			"grocery.shop-day"
		],
		"notificationKinds": [
			{
				"id": "expiring-digest",
				"channel": "in-app",
				"cadence": "daily",
				"default": true,
				"signal": "stock.expiring",
				"when": null
			},
			{
				"id": "low-stock",
				"channel": "in-app",
				"cadence": "weekly",
				"default": true,
				"signal": null,
				"when": null
			},
			{
				"id": "shop-day-reminder",
				"channel": "os",
				"cadence": "morning-of",
				"default": true,
				"signal": "grocery.shop-day",
				"when": null
			}
		],
		"schedules": [
			{
				"id": "morning",
				"name": "kitchen.morning",
				"daily": "08:00",
				"every": null
			}
		],
		"intents": [
			"kitchen.add-to-grocery"
		],
		"deviceCapabilities": [
			"camera",
			"os-notifications"
		],
		"palette": {
			"entries": [
				{
					"id": "kitchen.add-to-grocery",
					"verb": "run",
					"label": "domains.kitchen.grocery.add",
					"icon": "plus",
					"quickAction": "add-to-grocery"
				},
				{
					"id": "kitchen.capture-haul",
					"verb": "run",
					"label": "domains.kitchen.capture.action",
					"icon": "camera",
					"quickAction": "capture-haul"
				}
			],
			"search": [
				"stock-item",
				"recipe"
			]
		},
		"export": [
			"stock-item",
			"recipe",
			"grocery-list",
			"grocery-item",
			"storage-tip"
		]
	},
	"toolbench": {
		"id": "toolbench",
		"phase": 1,
		"name": "domains.toolbench.name",
		"subtitle": "domains.toolbench.subtitle",
		"sidebar": {
			"group": "shell",
			"order": 10,
			"visible": true
		},
		"tabs": [
			{
				"id": "ideas",
				"label": "domains.toolbench.tabs.ideas"
			},
			{
				"id": "projects",
				"label": "domains.toolbench.tabs.projects"
			},
			{
				"id": "lab",
				"label": "domains.toolbench.tabs.lab"
			},
			{
				"id": "studio",
				"label": "domains.toolbench.tabs.studio"
			},
			{
				"id": "notes",
				"label": "domains.toolbench.tabs.notes"
			}
		],
		"resources": [
			"skill",
			"owned-hardware",
			"preferred-tool",
			"idea",
			"project",
			"device",
			"parts-list",
			"sketch",
			"note",
			"brainstorm-session",
			"render"
		],
		"reads": [],
		"widgets": [
			{
				"id": "resurfaced-idea",
				"sizes": [
					"s"
				],
				"default": true,
				"planned": false,
				"reads": [
					"idea"
				],
				"title": "garden.widgets.resurfacedIdea",
				"empty": "garden.empty.resurfacedIdea"
			},
			{
				"id": "active-projects",
				"sizes": [
					"m"
				],
				"default": true,
				"planned": false,
				"reads": [
					"project"
				],
				"title": "garden.widgets.activeProjects",
				"empty": "garden.empty.activeProjects"
			},
			{
				"id": "recent-renders",
				"sizes": [
					"m"
				],
				"default": false,
				"planned": true,
				"reads": [
					"sketch",
					"render"
				],
				"title": "garden.widgets.recentRenders",
				"empty": "garden.empty.recentRenders"
			},
			{
				"id": "lab-status",
				"sizes": [
					"s"
				],
				"default": false,
				"planned": true,
				"reads": [
					"device"
				],
				"title": "garden.widgets.labStatus",
				"empty": "garden.empty.labStatus"
			}
		],
		"quickActions": [
			{
				"id": "capture-idea",
				"label": "domains.toolbench.ideas.capture",
				"icon": "lightbulb"
			}
		],
		"captureSources": [],
		"tools": [
			{
				"id": "brainstorm",
				"access": "read",
				"confirm": false,
				"reads": [
					"idea",
					"skill",
					"preferred-tool",
					"owned-hardware"
				]
			},
			{
				"id": "critique",
				"access": "read",
				"confirm": false,
				"reads": [
					"idea",
					"project"
				]
			},
			{
				"id": "expand-to-plan",
				"access": "write-draft",
				"confirm": false,
				"reads": [
					"idea",
					"project",
					"task"
				]
			},
			{
				"id": "find-similar",
				"access": "read",
				"confirm": false,
				"reads": [
					"idea",
					"project",
					"note"
				]
			},
			{
				"id": "estimate-parts-cost",
				"access": "read",
				"confirm": false,
				"reads": [
					"parts-list"
				]
			},
			{
				"id": "summarize-project",
				"access": "read",
				"confirm": false,
				"reads": [
					"project",
					"task"
				]
			},
			{
				"id": "draft-sketch-scaffold",
				"access": "write-draft",
				"confirm": false,
				"reads": [
					"sketch",
					"preferred-tool"
				]
			}
		],
		"signals": [
			"idea.stale",
			"project.updated"
		],
		"notificationKinds": [
			{
				"id": "stale-idea-nudge",
				"channel": "in-app",
				"cadence": "weekly",
				"default": false,
				"signal": null,
				"when": null
			}
		],
		"schedules": [],
		"intents": [
			"toolbench.open-idea"
		],
		"deviceCapabilities": [],
		"palette": {
			"entries": [
				{
					"id": "toolbench.capture-idea",
					"verb": "run",
					"label": "domains.toolbench.ideas.capture",
					"icon": "lightbulb",
					"quickAction": "capture-idea"
				}
			],
			"search": [
				"idea",
				"project",
				"note"
			]
		},
		"export": [
			"idea",
			"project",
			"device",
			"parts-list",
			"sketch",
			"note",
			"brainstorm-session"
		]
	},
	"weather": {
		"id": "weather",
		"phase": 1,
		"name": "domains.weather.name",
		"subtitle": "domains.weather.subtitle",
		"sidebar": {
			"group": "domains",
			"order": 20,
			"visible": true
		},
		"tabs": [],
		"resources": [
			"forecast",
			"alert",
			"ephemeris",
			"air-quality",
			"allergens"
		],
		"reads": [
			"home-area",
			"workout-session",
			"outing"
		],
		"widgets": [
			{
				"id": "weather-now",
				"sizes": [
					"s",
					"m"
				],
				"default": true,
				"planned": false,
				"reads": [
					"forecast"
				],
				"title": "garden.widgets.weatherNow",
				"empty": "garden.empty.weatherNow"
			},
			{
				"id": "sun-and-moon",
				"sizes": [
					"s"
				],
				"default": true,
				"planned": false,
				"reads": [
					"ephemeris"
				],
				"title": "garden.widgets.sunAndMoon",
				"empty": "garden.empty.sunAndMoon"
			},
			{
				"id": "week-outlook",
				"sizes": [
					"m"
				],
				"default": false,
				"planned": true,
				"reads": [
					"forecast"
				],
				"title": "garden.widgets.weekOutlook",
				"empty": "garden.empty.weekOutlook"
			},
			{
				"id": "good-day-for",
				"sizes": [
					"s"
				],
				"default": false,
				"planned": true,
				"reads": [
					"forecast",
					"air-quality",
					"allergens"
				],
				"title": "garden.widgets.goodDayFor",
				"empty": "garden.empty.goodDayFor"
			}
		],
		"quickActions": [],
		"captureSources": [],
		"tools": [
			{
				"id": "forecast",
				"access": "read",
				"confirm": false,
				"reads": [
					"forecast",
					"home-area",
					"venue"
				]
			},
			{
				"id": "rain-during-plan",
				"access": "read",
				"confirm": false,
				"reads": [
					"forecast",
					"home-area",
					"workout-session",
					"local-event",
					"outing"
				]
			},
			{
				"id": "sun-and-moon",
				"access": "read",
				"confirm": false,
				"reads": [
					"ephemeris"
				]
			}
		],
		"signals": [
			"weather.alert",
			"weather.rain-before-plan",
			"weather.frost"
		],
		"notificationKinds": [
			{
				"id": "severe-alert",
				"channel": "os",
				"cadence": "on-issue",
				"default": true,
				"signal": "weather.alert",
				"when": {
					"severity": [
						"severe",
						"extreme"
					]
				}
			},
			{
				"id": "rain-before-plans",
				"channel": "in-app",
				"cadence": "evening-before",
				"default": true,
				"signal": null,
				"when": null
			},
			{
				"id": "frost-warning",
				"channel": "in-app",
				"cadence": "evening-before",
				"default": true,
				"signal": null,
				"when": null
			}
		],
		"schedules": [
			{
				"id": "alerts",
				"name": "weather.alerts",
				"daily": null,
				"every": 300
			}
		],
		"intents": [],
		"deviceCapabilities": [
			"os-notifications"
		],
		"palette": {
			"entries": [],
			"search": []
		},
		"export": []
	}
} as const

/** What the shell declares for itself. */
export const SHELL = {
	"domains": [
		"kitchen",
		"toolbench",
		"weather"
	],
	"sidebar": {
		"groups": [
			"today",
			"shell",
			"domains"
		],
		"entries": [
			{
				"id": "today",
				"name": "shell.today",
				"subtitle": "shell.todaySubtitle",
				"group": "today",
				"order": 0,
				"place": true,
				"key": null
			},
			{
				"id": "garden",
				"name": "shell.garden",
				"subtitle": "shell.gardenSubtitle",
				"group": "shell",
				"order": 0,
				"place": true,
				"key": null
			},
			{
				"id": "gardener",
				"name": "shell.gardener",
				"subtitle": "shell.gardenerSubtitle",
				"group": "shell",
				"order": 5,
				"place": false,
				"key": "G"
			}
		],
		"pinned": [
			{
				"id": "settings",
				"name": "shell.settings",
				"subtitle": "shell.settingsSubtitle",
				"key": ","
			}
		]
	},
	"tabs": {
		"places": [
			"garden",
			"today"
		],
		"pinned": [
			"kitchen",
			"weather"
		],
		"more": {
			"id": "more",
			"name": "shell.more"
		}
	},
	"tiles": [
		{
			"id": "today",
			"glyph": "today",
			"sizes": [
				"m"
			],
			"reads": [
				"task"
			],
			"title": "garden.widgets.today",
			"empty": "garden.empty.today"
		},
		{
			"id": "daily-line",
			"glyph": "garden",
			"sizes": [
				"m"
			],
			"reads": [],
			"title": "garden.widgets.dailyLine",
			"empty": "garden.empty.dailyLine"
		},
		{
			"id": "quick-log",
			"glyph": "fitness",
			"sizes": [
				"s"
			],
			"reads": [
				"body-metric"
			],
			"title": "garden.widgets.quickLog",
			"empty": "garden.empty.quickLog"
		}
	],
	"gardenDefault": [
		"weather-now",
		"today",
		"expiring-soon",
		"cook-tonight",
		"resurfaced-idea",
		"active-projects",
		"sun-and-moon",
		"daily-line",
		"quick-log"
	]
} as const
